#!/usr/bin/env python3
"""Regenerate marathon-ui/Core/PhosphorGlyphs.js from the Phosphor Light CSS.

Usage:
  ./scripts/build-phosphor-glyphs.py <path/to/phosphor-light/style.css>

The CSS is shipped in the @phosphor-icons/web release tarball under
src/light/style.css. This script parses the codepoints out of the
`.ph-light.ph-NAME:before { content: "\eXXX" }` rules and emits a
QML .pragma library JS module containing one map: Glyphs[name] → "\uXXXX".

The map exposes:
  • Every Phosphor Light icon by its canonical name (1500+).
  • A curated set of Lucide → Phosphor name aliases so Marathon QML can
    keep using `name: "chevron-right"` after the Phosphor migration without
    a code-wide rename.
"""

import json, re, sys
from pathlib import Path

# Lucide → Phosphor name overrides. Keys are names used in Marathon QML
# (mostly Lucide kebab-case carried over from the pre-Phosphor era); values
# are Phosphor Light glyph names. The translations follow the design
# system's PHOSPHOR_NAME_MAP in shell.jsx, extended for the icons Marathon
# QML actually references.
ALIASES = {
    "alert-circle":      "warning-circle",
    "alert-triangle":    "warning",
    "arrow-down-up":     "arrows-down-up",
    "battery":           "battery-full",
    "bell-ring":         "bell-ringing",
    "cable":             "plug",
    "chevron-left":      "caret-left",
    "chevron-right":     "caret-right",
    "chevron-up":        "caret-up",
    "chevron-down":      "caret-down",
    "circle-check":      "check-circle",
    "corner-down-left":  "arrow-elbow-down-left",
    "delete":            "backspace",
    "ellipsis-vertical": "dots-three-vertical",
    "eye-off":           "eye-slash",
    "filter":            "funnel",
    "grid":              "squares-four",
    "grid-3x3":          "grid-four",
    "hard-drive":        "hard-drives",
    "home":              "house",
    "inbox":             "tray",
    "layers":            "stack",
    "layout-grid":       "squares-four",
    "locked":            "lock-key",
    "message-circle":    "chat-circle",
    "message-square":    "chat-text",
    "music":             "music-note",
    "music-2":           "music-notes",
    "navigation":        "navigation-arrow",
    "plane":             "airplane",
    "refresh-cw":        "arrows-clockwise",
    "rotate-ccw":        "arrow-counter-clockwise",
    "rotate-cw":         "arrow-clockwise",
    "search":            "magnifying-glass",
    "send":              "paper-plane-right",
    "settings":          "gear",
    "settings-2":        "sliders-horizontal",
    "shield-alert":      "shield-warning",
    "signal":            "cell-signal-high",
    "smartphone":        "device-mobile",
    "sparkles":          "sparkle",
    "spell-check":       "check-fat",
    "terminal":          "terminal-window",
    "trash-2":           "trash",
    "trending-up":       "trend-up",
    "undo-2":            "arrow-u-up-left",
    "vibrate":           "device-mobile-camera",
    "video":             "video-camera",
    "volume-2":          "speaker-high",
    "wifi":              "wifi-high",
    "active":            "circle",
    "activity":          "pulse",
    "app":               "squares-four",
    "brightness":        "sun",
    "download":          "download-simple",
    "mail":              "envelope",
    "map":               "map-trifold",
    "menu":              "list",
    "move":              "arrows-out-cardinal",
}


def parse_codepoints(css_path):
    css = Path(css_path).read_text()
    rx = re.compile(r'\.ph(?:-light)?\.ph-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"')
    return {m.group(1): m.group(2) for m in rx.finditer(css)}


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    glyphs = parse_codepoints(sys.argv[1])
    print(f"// found {len(glyphs)} Phosphor icons", file=sys.stderr)

    flat = {}
    for name, hex_cp in glyphs.items():
        flat[name] = "\\u" + hex_cp.upper().zfill(4)
    for alias, target in ALIASES.items():
        hex_cp = glyphs.get(target)
        if not hex_cp:
            print(f"WARN: alias {alias} → {target} (no glyph)", file=sys.stderr)
            continue
        flat[alias] = "\\u" + hex_cp.upper().zfill(4)

    out = Path("marathon-ui/Core/PhosphorGlyphs.js")
    with out.open("w") as f:
        f.write('.pragma library\n')
        f.write('// Auto-generated by scripts/build-phosphor-glyphs.py from Phosphor Light.\n')
        f.write('// Do not edit by hand. To change aliases, edit the ALIASES table in\n')
        f.write('// the script and re-run it.\n')
        f.write('var Glyphs = {\n')
        for k in sorted(flat.keys()):
            f.write(f'    "{k}": "{flat[k]}",\n')
        f.write('};\n')
    print(f"wrote {out} ({len(flat)} entries)", file=sys.stderr)


if __name__ == "__main__":
    main()
