name: Code Format Check

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    permissions:
      pull-requests: write

    steps:
      - name: Install packages
        run: |
          pacman -Syu --noconfirm git clang qt6-declarative

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run formatters
        id: format
        continue-on-error: true
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          echo "=== Running clang-format ==="
          clang-format -i $(git ls-files '*.cpp' '*.h')

          echo "=== Running qmlformat ==="
          /usr/lib/qt6/bin/qmlformat -i $(git ls-files '*.qml')

          if [[ -n $(git status --porcelain) ]]; then
            echo "needs_formatting=true" >> $GITHUB_OUTPUT
          else
            echo "needs_formatting=false" >> $GITHUB_OUTPUT
          fi

      - name: Post comment on PR if needed
        if: github.event_name == 'pull_request' && steps.format.outputs.needs_formatting == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            **Formatting changes required**
            This PR does not follow the formatting rules.
            Please run:
            ```bash
            clang-format -i <files>
            qmlformat -i <files> (must be from Qt 6)
            ```
            Commit the updated files and push again.

      - name: Fail job
        if: steps.format.outputs.needs_formatting == 'true'
        run: |
          echo "Formatting required. Failing."
          exit 1
